### ISSUE TITLE
Four player printing problem

### ISSUE THREAD

**Issue by mosesncsu** [nickv2002/Imperial-Assault-Skirmish-Map-Project#3]
I went to pixart and completed the same process that I had for a previous printing, but recieved the following message:

"The dimensions of the file do not correspond to those selected in the order; the order is for 49.319 x 30.531 in, but the file you uploaded measures 205.5 X 127.22 inches. It appears that there is white patch in the left bottom of the artwork."

I resubmitted the fourplayer.jpg file, but received the same message. I do not have the technical understanding to actually figure out where the problem is, unfortunately.

**Comment by nickv2002** [comment]
Thanks for letting me know about this @mosesncsu 
I think this was a bug on my part: the _FourPlayer.jpg_ file didn't have the right metadata indicating it was 300 DPI so PixArt would reject it. [I've uploaded a new version to this repository](https://github.com/nickv2002/Imperial-Assault-Skirmish-Map-Project/raw/master/Combined_IA_Map_Sheets/FourPlayer/FourPlayer.jpg) that you should download and resubmit.

Please let me know if you continue to have any problems.

**Comment by mosesncsu** [comment]
Thanks so much! Forgot to mention how much I appreciate the work of you and others to make this game accessible. Great job!!
