### ISSUE TITLE
Coruscant Back Alley errata

### ISSUE THREAD

**Issue by tnaskali** [nickv2002/Imperial-Assault-Skirmish-Map-Project#5]
According to page 11 of [the latest FAQ](https://github.com/nickv2002/Imperial-Assault-Skirmish-Map-Project) both "The Triple Cross" and "Propaganda War" have text errata, but the images still show the original text.

**Comment by nickv2002** [comment]
Should be fixed with https://github.com/nickv2002/Imperial-Assault-Skirmish-Map-Project/commit/74b47c9eea11dbde011250221395b32ea808922a
Thanks for reporting
