### ISSUE TITLE
The Malastarian Outpost - Raid Map Image

### ISSUE THREAD

**Issue by pablogfb** [nickv2002/Imperial-Assault-Skirmish-Map-Project#6]
It would be great having both maps in one set. Is there any plan about it?

**Comment by nickv2002** [comment]
Thanks for your question.

We don't have _The Malastarian Outpost_ Raid map image yet. If someone is interested in doing the image editing to put that together I can share the scans I have of the tiles. (I don't have much time for this at the moment.)
Once that's created it's very easy to put them into a set together and I will do that.

(I'm changing the issue title to reflect this ⬆️ )

**Comment by nickv2002** [comment]
This map was added thanks to hard work by El_Lalotreto back in July 2020 and I forgot to close this ticket!
